@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RhOGRhNDhkZGMyNTdlZDdhODM2MGIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjY5NTE5NSwiZXhwIjoxNzQ2NzAyMzk1fQ.AItk9hacrfLwYS-vNg0inOUa4C5enMpZsq5k54QYG_0
@token_2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFjNzRlOGE3MzdiZGQ1NGE4NGE2NmEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjY5NTU4NiwiZXhwIjoxNzQ2NzAyNzg2fQ.YTSfxoq_g7Pf1L21cdE8Aj06sDYW3Y1yr5m0QsU3vAY

@client_id = 681c74b4a737bdd54a84a663
@user_id = 67da8da48ddc257ed7a8360b

### GET client by ID (or all clients with no ID)
GET http://localhost:3000/api/client/
Authorization: Bearer {{token}}

###

### POST create a new client
POST http://localhost:3000/api/client
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_id" : "{{user_id}}",
    "email" : "miguel@gmail.com",
    "name" : "Miguel",
    "lastname" : "Rios",
    "address" : "C/ Ejemplo 123",
    "deleted" : false
}

###

### PATCH update a client
PATCH http://localhost:3000/api/client/{{client_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name" : "John"
}

###

### DELETE (archive?) a client
DELETE http://localhost:3000/api/client/{{client_id}}?soft=true
Authorization: Bearer {{token}}

###

### GET archived clients
GET http://localhost:3000/api/client/archived
Authorization: Bearer {{token}}

###

### PUT restore an archived client
PUT http://localhost:3000/api/client/{{client_id}}/restore
Authorization: Bearer {{token}}