@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RhOGRhNDhkZGMyNTdlZDdhODM2MGIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjY5NTE5NSwiZXhwIjoxNzQ2NzAyMzk1fQ.AItk9hacrfLwYS-vNg0inOUa4C5enMpZsq5k54QYG_0
@token_2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFjNzRlOGE3MzdiZGQ1NGE4NGE2NmEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjY5NTU4NiwiZXhwIjoxNzQ2NzAyNzg2fQ.YTSfxoq_g7Pf1L21cdE8Aj06sDYW3Y1yr5m0QsU3vAY

@deliverynote_id = 681c7786a737bdd54a84a6a6
@project_id = 681b80e8e6e8c7fa84cd6f19
@client_id = 681c74b4a737bdd54a84a663

### GET delivery note by ID
GET http://localhost:3000/api/deliverynote/
Authorization: Bearer {{token}}

###

### POST create a new delivery note
POST http://localhost:3000/api/deliverynote
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "project_id" : "{{project_id}}",
    "data" : [
        {
            "type" : "material",
            "name" : "Bricks",
            "quantity" : 10
        },
        {
            "type" : "person",
            "name" : "John Doe",
            "quantity" : 2
        }
    ],
    "signature" : null,
    "deleted" : false
}

###

### GET delivery notes by client ID
GET http://localhost:3000/api/deliverynote/client/{{client_id}}
Authorization: Bearer {{token}}

###

### GET delivery notes by project ID
GET http://localhost:3000/api/deliverynote/project/{{project_id}}
Authorization: Bearer {{token}}

###

### GET delivery note PDF by ID
GET http://localhost:3000/api/deliverynote/pdf/{{deliverynote_id}}
Authorization: Bearer {{token}}

###

### PUT upload signature to delivery note
PUT http://localhost:3000/api/deliverynote/signature/{{deliverynote_id}}
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="signature.png"
Content-Type: image/png

< ./multimedia/signature.png
--boundary--

###

### DELETE (archive) a delivery note
DELETE http://localhost:3000/api/deliverynote/{{deliverynote_id}}?soft=false
Authorization: Bearer {{token}}