### Signup
POST http://localhost:3000/api/user
Content-Type: application/json

{
    "email": "riosmarcosmiguel@gmail.com",
    "password": "12345678"
}

### Validation
PUT http://localhost:3000/api/user/validation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFjNzRlOGE3MzdiZGQ1NGE4NGE2NmEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjY5NTQwMCwiZXhwIjoxNzQ2NzAyNjAwfQ.HMWwjLkOmBco4Emyz-Q6vtklkd4wS7iTH67ocpti258

{
    "code": "25d29c"
}

### Login
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "riosmarcosmiguel@gmail.com",
    "password": "12345678"
}

### Update user info
PATCH http://localhost:3000/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RhOGRhNDhkZGMyNTdlZDdhODM2MGIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MjM3NjQ4MSwiZXhwIjoxNzQyMzgzNjgxfQ.UGlRW2-CAjRLqpVkjAVphKQaqcLEs94-D0nBIXRK91g

{
    "name" : "John",
    "lastname" : "Doe",
    "nif" : "12345678Z"
}

### User company (Autónomo)
PUT http://localhost:3000/api/user/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RhOGRhNDhkZGMyNTdlZDdhODM2MGIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MjM3NjQ4MSwiZXhwIjoxNzQyMzgzNjgxfQ.UGlRW2-CAjRLqpVkjAVphKQaqcLEs94-D0nBIXRK91g

{
    "company": false
}

### User company (No autónomo)
PUT http://localhost:3000/api/user/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RhOGRhNDhkZGMyNTdlZDdhODM2MGIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MjM3NjQ4MSwiZXhwIjoxNzQyMzgzNjgxfQ.UGlRW2-CAjRLqpVkjAVphKQaqcLEs94-D0nBIXRK91g

{
    "company" : {
        "name" : "Empresa test",
        "cif" : "12345678Z",
        "address" : {
            "street" : "Calle test",
            "number" : 1,
            "postalCode" : 28001,
            "city" : "Madrid",
            "province" : "Madrid"
        }
    }
}

### User logo
PUT http://localhost:3000/api/user/logo
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RhOGRhNDhkZGMyNTdlZDdhODM2MGIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MjQ2NzU2NCwiZXhwIjoxNzQyNDc0NzY0fQ.dFSwVuziYPgAi51R495bX_iK1s02enabZ6qADXPpP9I

--boundary
Content-Disposition: form-data; name="file"; filename="test_user_logo.png"
Content-Type: image/png

< ./test_user_logo.png
--boundary--

### Get user info
GET http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RhOGRhNDhkZGMyNTdlZDdhODM2MGIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjY5NTE5NSwiZXhwIjoxNzQ2NzAyMzk1fQ.AItk9hacrfLwYS-vNg0inOUa4C5enMpZsq5k54QYG_0

### Delete user
DELETE http://localhost:3000/api/user?soft=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RhOGRhNDhkZGMyNTdlZDdhODM2MGIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MjQ2NzU2NCwiZXhwIjoxNzQyNDc0NzY0fQ.dFSwVuziYPgAi51R495bX_iK1s02enabZ6qADXPpP9I

### Soft delete user
DELETE http://localhost:3000/api/user?soft=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RhOGRhNDhkZGMyNTdlZDdhODM2MGIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MjQ2NzU2NCwiZXhwIjoxNzQyNDc0NzY0fQ.dFSwVuziYPgAi51R495bX_iK1s02enabZ6qADXPpP9I

### Generate recovery token
POST http://localhost:3000/api/user/recovery
Content-Type: application/json

{
    "email" : "miguel12105marcos@gmail.com"
}

### Update user password
PUT http://localhost:3000/api/user/password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RhOGRhNDhkZGMyNTdlZDdhODM2MGIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0Mjk4MjIyNCwiZXhwIjoxNzQyOTg5NDI0fQ.p9K8Cpb8nFvWOGBlaACsel5iShh14ncH0itU14uz05s
Content-Type: application/json

{
    "password" : "12345678"
}

### Add guest to the company
POST http://localhost:3000/api/user/company/guest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RhOGRhNDhkZGMyNTdlZDdhODM2MGIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MzA3MDQzNSwiZXhwIjoxNzQzMDc3NjM1fQ.paLS2u5grUPGO4h1xUiernwzl8KRLdclgnWqBqgL0W4
Content-Type: application/json

{
    "email": "jopetis28@gmail.com",
    "password": "12345678",
    "name" : "John",
    "lastname" : "Doe",
    "nif" : "12345678Z"
}